#
#        GENERATE BY NODEFONY CONFIG BUNDLE YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/



########## NODEFONY CONFIG BUNDLE  realTimeBundle  ############
name :				realTimeBundle
locale :			en_en
version :                       "beta"

 
system:
  reconnect:
    handshake:                  false
    connect:                    true 
#  bufferSize:                   650000  

            
#https://github.com/Worlize/WebSocket-Node/wiki/Documentation
httpBundle:
  websocket:
    keepaliveInterval:            1000
    keepaliveGracePeriod:         1000

  websocketSecure:
    keepaliveInterval:            1000
    keepaliveGracePeriod:         1000


services:                         ~
