realSecure:
  pattern:   /secure/realtime   
  defaults: {"controller": "realTimeBundle:default:index"}
  requirements: 
    method: GET,POST,WEBSOCKET

real:
  pattern:   /realtime   
  defaults: {"controller": "realTimeBundle:default:index"}
  requirements: 
    method: GET,POST,WEBSOCKET

