########## nodefony CONFIG BUNDLE  mongooseBundle  ############
type        :               "nodefony"
locale      :               en_en


#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true            # by default services false !
#    or
#      watch:
#        controllers     :  true
#        config         :   true		# only  routing
#        views          :   true
#        translations   :   true
#        webpack        :   true
#        services       :   true
watch       :               false

mongoose:
  debug:                    false
  # // sync || migrate || none  when nodefony build  or  nodefony install
  strategy:                 "none"
  connectors:
    nodefony:
      host:                 "127.0.0.1"
      port:                 27017
      dbname:               "nodefony"
      settings:
        #user:              "nodefony"
        #pass:              "nodefony"
        #reconnectTries:    100
        #reconnectInterval: 5000
        #autoReconnect:     true
