language: node_js

os:
  - linux
#  - osx
  
sudo: true

node_js:
  - "6"
  - "7"
  
services:
  - mysql
  - memcached
  - elasticsearch
  
env:
  - DB=sqlite
  - DB=mysql
  
before_script:
  - sleep 10
  
before_install:
  - sudo apt-get install nginx -y
  - mysql -e "create database IF NOT EXISTS nodefony;" -uroot
  - "curl -L https://raw.githubusercontent.com/nodefony/nodefony/dev/.travis/bin/install.sh | /bin/sh"

branches:
  only:
  - master

cache:
  directories:
    - node_modules # NPM packages


addons:
  hosts:
    - nodefony.com
  apt:
    sources: [ 'ubuntu-toolchain-r-test']
    packages: ['libstdc++6']

install: true

test: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d1095f0637a609e290a2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
