#!/usr/bin/env node
const asciify = require('asciify');

// nodefony
try {
	const nodefony  = require("nodefony");
}catch(e){
	const nodefony = require(".", "src", "nodefony", "core", "autoloader");
}

// START CONSOLE
asciify("      NODEFONY", {font:'standard'}, function(err, res){

	console.log('\033[31m'+res+'\033[0m');

	process.env["MODE_START"] = "NODEFONY_CONSOLE" ;

	const kernel = new nodefony.console( "prod", false, {
		node_start:process.env["MODE_START"]
	});
});
