#!/usr/bin/env node
// --expose-gc --trace-gc --log-gc --trace-gc-verbose
//--debug

const path = require("path");
const fs = require("fs");
const shell = require("shelljs");

///*var profiler = require('v8-profiler');
//var heapdump = require('heapdump');
//heapdump.writeSnapshot(process.cwd()+'/tmp/' + Date.now() + '.heapsnapshot', function(err, filename) {
//	console.log('heapdump written to', filename);
//});*/

/*
 *
 * NODEFONY FRAMEWORK
 *
 *	DEVELOPPEMENT
 *
 */
try {
	const nodefony = require("nodefony");
}catch(e){
	const nodefony = require(".", "src", "nodefony", "core", "autoloader");
}
var links = path.resolve( ".", "tmp", "assestLink" ) ;
if ( fs.existsSync( links) ){
	shell.rm("-Rf", links);
}
var environment = "dev" ;
var debug = true ;
if ( process.env["NODEFONY_DEBUG"] ){
	debug = process.env["NODEFONY_DEBUG"] ;
}
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
process.env["MODE_START"] = "NODEFONY_DEV" ;

// KERNEL
const kernel = new nodefony.appKernel("SERVER", environment, debug, {
		node_start:process.env["MODE_START"],
		logSpinner:false
});

return kernel ;
