#
#
#	CONFIG BUNDLE testBundle
#
#===============================================================================
#
#  Copyright © 2016/2017         |
#
# ===============================================================================
#
#        GENERATE BY nodefony BUILDER YAML FILE
#
# This file is YAML  FILE
# ---
# YAML:         YAML Ain't Markup Language
#
# What It Is:   YAML is a human friendly data serialization
#   standard for all programming languages.
#
#
#

########## nodefony CONFIG BUNDLE  testBundle  ############
name :				testBundle
locale :			en_en

#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        config: true		# only  routing.yml
#        views:			true
#        translations: true
#
watch:
  controller:		true
  config:       true
  views:			  true
  translations: true
  services:     true

#
#
#	Insert here the bundle-specific configurations
#
#	You can also override config of another bundle
#	with the name of the bundle
#
#	example :     create an other database connector
#
