#
#
#  ROUTING BUNDLE testBundle
#
########## nodefony ROUTING  testBundle  ############

test:
  pattern:  /test
  defaults: {"controller": "testBundle:default:index"}

test-json:
  pattern:  /json
  defaults: {"controller": "testBundle:default:json"}

test-rest:
  pattern:  /rest
  defaults: {"controller": "testBundle:default:rest"}

test-watcher:
    pattern:  /test/watcher
    defaults: {"controller": "testBundle:default:watcher"}

### WEBSOCKET ###
test-websoket:
  pattern:  /websoket
  defaults: {"controller": "testBundle:default:websoket"}
  requirements:
    method:
      - WEBSOCKET
test-websoket-code:
  pattern:  /test/unit/websocket/{code}
  defaults: {"controller": "testBundle:websocket:websocket"}
  requirements:
      code:       "^\\d{3}$"
      method:
          - WEBSOCKET

test-websoket-protocol:
  pattern:  /test/unit/websocket/protocol/telnet
  defaults: {"controller": "testBundle:websocket:protocol"}
  requirements:
      method:
          - WEBSOCKET
      protocol: "telnet"

test-websoket-protocol-sip:
  pattern:  /test/unit/websocket/protocol/sip
  defaults: {"controller": "testBundle:websocket:protocolSip"}
  requirements:
      method:
          - WEBSOCKET
      protocol: "sip"

test-websoket-cors:
  pattern:  /test/unit/websocket/cors
  defaults: {"controller": "testBundle:websocket:cors"}
  requirements:
      method:
          - WEBSOCKET
      protocol: "sip"


response-status:
  pattern:      /test/unit/response/status/{st}
  defaults:     {"controller": "testBundle:test:responseStatus"}
  requirements:
    method:     GET

response-message:
  pattern:      /test/unit/response/status/{st}/{message}
  defaults:     {"controller": "testBundle:test:responseMessage","message":bar}
  requirements:
    method:     GET

response-query:
  pattern:      /test/unit/response/query/{myVariable}/{myVariable2}
  defaults:     {"controller": "testBundle:test:responseQuery","myVariable":foo,"myVariable2":bar}
  requirements:
    method:     GET

redirect-301:
  pattern:      /test/unit/redirect/{status}
  defaults:     {"controller": "testBundle:controllerTest:redirect","status":302}
  requirements:
    method:
      - GET
      - POST

request-data:
  pattern:      /test/unit/request
  defaults:     {"controller": "testBundle:controllerTest:request"}
  requirements:
    method:
      - GET
      - POST

request-multi-part:
  pattern:      /test/unit/request/multipart
  defaults:     {"controller": "testBundle:multipart:requestMultiPart"}

request-promise:
  pattern:      /test/unit/promise/{action}
  defaults:     {"controller": "testBundle:controllerTest:promise", "action":"promise"}
  requirements:
    method:
      - GET
      - POST

request-exception:
  pattern:      /test/unit/exception/{action}
  defaults:     {"controller": "testBundle:controllerTest:exception", "action":500}
  requirements:
    method:
      - GET
      - POST

subrequest:
  pattern:      /test/unit/subrequest
  defaults:     {"controller": "testBundle:subRequest:index" }
  requirements:
    method:     GET


# LOGIN
test-login:
  pattern:      /test/login
  defaults:     {"controller": "testBundle:login:login"}
test-logout:
  pattern:      /test/logout
  defaults:     {"controller": "testBundle:login:logout"}
