#
#
#  ROUTING BUNDLE testBundle
#
########## nodefony ROUTING  testBundle  ############

test:
  pattern:  /test
  defaults: {"controller": "testBundle:default:index"}

test-json:
  pattern:  /json
  defaults: {"controller": "testBundle:default:json"}

test-rest:
  pattern:  /rest
  defaults: {"controller": "testBundle:default:rest"}

test-watcher:
    pattern:  /test/watcher
    defaults: {"controller": "testBundle:default:watcher"}

### WEBSOCKET ###
test-websoket:
  pattern:  /websoket
  defaults: {"controller": "testBundle:default:websoket"}
  requirements:
    method:
      - WEBSOCKET
test-websoket-404:
  pattern:  /test/websocket
  defaults: {"controller": "testBundle:default:websoket"}
  requirements:
      method:
          - WEBSOCKET

## UNIT TEST
myroute:
  pattern:      /myroute
  defaults:     {"controller": "testBundle:test:myroute","page":51,"elements":"defaultValue"}
  requirements:
    method:     GET
    page:       "^\\d\\d$"

myroute2:
  pattern:      /myroute/{page}/{elements}
  defaults:     {"controller": "testBundle:test:myroute","page":13,"elements":"myRouteDefaultValue"}
  requirements:
    method:     GET
    page:       "^\\d\\d$"

myroute-*:
  pattern:      /wildcard/*
  defaults:     {"controller": "testBundle:test:wildcard"}

myroute-*1:
  pattern:      /wildcard1*
  defaults:     {"controller": "testBundle:test:wildcard"}

myroute-*2:
  pattern:      /wildcard2/{*}
  defaults:     {"controller": "testBundle:test:wildcard"}

myroute-*3:
  pattern:      /wildcard3/{*}/route2
  defaults:     {"controller": "testBundle:test:wildcard"}

myroute-*4:
  pattern:      /wildcard4/{*}/route2/{*}/test
  defaults:     {"controller": "testBundle:test:wildcard"}

response-status:
  pattern:      /test/unit/response/status/{st}
  defaults:     {"controller": "testBundle:test:responseStatus"}
  requirements:
    method:     GET

response-message:
  pattern:      /test/unit/response/status/{st}/{message}
  defaults:     {"controller": "testBundle:test:responseMessage","message":bar}
  requirements:
    method:     GET

response-query:
  pattern:      /test/unit/response/query/{myVariable}/{myVariable2}
  defaults:     {"controller": "testBundle:test:responseQuery","myVariable":foo,"myVariable2":bar}
  requirements:
    method:     GET

redirect-301:
  pattern:      /test/unit/redirect/{status}
  defaults:     {"controller": "testBundle:controllerTest:redirect","status":302}
  requirements:
    method:
      - GET
      - POST

request-data:
  pattern:      /test/unit/request
  defaults:     {"controller": "testBundle:controllerTest:request"}
  requirements:
    method:
      - GET
      - POST

request-promise:
  pattern:      /test/unit/promise/{action}
  defaults:     {"controller": "testBundle:controllerTest:promise", "action":"promise"}
  requirements:
    method:
      - GET
      - POST

request-exception:
  pattern:      /test/unit/exception/{action}
  defaults:     {"controller": "testBundle:controllerTest:exception", "action":500}
  requirements:
    method:
      - GET
      - POST

twig-render:
  pattern:      /test/unit/twig/render
  defaults:     {"controller": "testBundle:twig:render"}
  requirements:
    method:
      - GET
      - POST

twig-extend:
  pattern:      /test/unit/twig/extend
  defaults:     {"controller": "testBundle:twig:extend"}
  requirements:
    method:
      - GET
      - POST

twig-websocket:
  pattern:      /test/unit/twig/websocket
  defaults:     {"controller": "testBundle:twig:websocket"}
  requirements:
    method:
      - GET
      - POST
      - WEBSOCKET

session:
  pattern:      /test/unit/session/{type}
  defaults:     {"controller": "testBundle:session:session" , "type":"callback"}
  requirements:
    method:
      - GET
      - POST
      - WEBSOCKET

subrequest:
  pattern:      /test/unit/subrequest
  defaults:     {"controller": "testBundle:subRequest:index" }
  requirements:
    method:     GET

myroute-requirement-method-get:
  pattern:      /requirement/method
  defaults:     {"controller": "testBundle:test:requirementMethod"}
  requirements:
    method:     GET

myroute-requirement-method-post:
  pattern:      /requirement/method
  defaults:     {"controller": "testBundle:test:requirementMethod"}
  requirements:
    method:     POST

rest-401:
  pattern:      /test/unit/rest/401
  defaults:     {"controller": "testBundle:rest:401"}

rest-403:
  pattern:      /test/unit/rest/403
  defaults:     {"controller": "testBundle:rest:403"}

# LOGIN
test-login:
  pattern:      /test/login
  defaults:     {"controller": "testBundle:login:index"}
test-logout:
  pattern:      /test/logout
  defaults:     {"controller": "testBundle:login:logout"}

# FIREWALL
test-sasl-area:
  pattern:      /test/firewall/sasl
  defaults:     {"controller": "testBundle:firewall:sasl"}

test-basic-area:
  pattern:      /test/firewall/basic
  defaults:     {"controller": "testBundle:firewall:basic"}

test-digest-area:
  pattern:      /test/firewall/digest
  defaults:     {"controller": "testBundle:firewall:digest"}

test-local-area:
  pattern:      /test/firewall/local
  defaults:     {"controller": "testBundle:firewall:local"}
