########## NODEFONY CONFIG BUNDLE  frameworkBundle  ############
name :				frameworkBundle

#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        views:			true
#        translations:      true
#
watch:                      false


webpack:
  cache:                    false
  watchOptions:
    ignoreInitial:          false
    persistent:             true
    followSymlinks:         false
    depth:                  0
    atomic:                 false
    alwaysStat:             true
    ignorePermissionErrors: true
