########## NODEFONY CONFIG BUNDLE  frameworkBundle  ############
name :				frameworkBundle
version :			"Beta"

# webpack assets root path is ./Resources/public
webpack:
  entry:
    main:                       "./js/framework.js"
  watch:                        false
  devtool:                      "source-map"
  output:
    filename:                   "./assets/js/framework.js"
    library:                    "framework"
    libraryTarget:              "umd"

