# Security
security:
    #
    #  FIREWALL strategy
    #  when change security context (multi firewalls areas)
    #
    #  Strategy can be :       none, migrate, invalidate
    #
    session_fixation_strategy: migrate
    #
    #  FIREWALL  AREAS
    #
    firewalls:                 ~
    #
    #  FIREWALL  PROVIDER
    #
    providers:
      nodefony:
        entity:
          name:                "user"
