#
#        nodefony BUILDER YAML FILE
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#


########## NODEFONY CONFIG BUNDLE  demoBundle  ############
name :				demoBundle
locale :			en_en
version :           "1.0.0"

#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        config:                true
#        views:			true
#        translations:          true
#
watch:                          false


#
#  OVERRIDE BUNDLE REALTIME
#
realTimeBundle:
  system:
    reconnect:
      handshake:                  true
      connect:                    true
  services:
    random:
      type:                       tcp
      port:                       1315
      domain:                     localhost
    dmsg:
      type:                       tcp
      port:                       1316
      domain:                     localhost
