#
#
#	ROUTING BUNDLE demoBundle 
#
#===============================================================================
#
#  Copyright © /2016         | 
#
# ===============================================================================
#
#        GENERATE BY App BUILDER YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/


#################################
#      ROUTING  demoBundle      #
#################################

### HOME ###
home: 
  pattern:  /
  defaults: {"controller": "demoBundle:demo:index"}

### MANAGE  DOCUMENTATION  ###
documentation: 
  pattern:  /documentation
  defaults: {"controller": "demoBundle:demo:readme"}

### MANAGE  LOGIN AND CREATE ACCOUNT NOT SECURE  ###
loginAll: 
  pattern:  /login/{type}
  defaults: {"controller": "demoBundle:login:login"}

subscribe: 
  pattern:  /subscribe
  defaults: {"controller": "demoBundle:login:subscribe"}
	
### MANAGE SECURE FOR AJAX CHALENGE AND FORM VALID ###
demoSecure: 
  pattern:  /demo/secure
  defaults: {"controller": "frameworkBundle:default:401"}

adduser: 
  pattern:  /adduser
  defaults: {"controller": "demoBundle:demo:addUser"}
  requirements: 
    method: POST 

demoLogout: 
  pattern:  /logout
  defaults: {"controller": "securityBundle:logout:logout"}

### ROUTE SECURE  FIRWALL AREA ###
saslArea: 
  pattern:  /demo
  defaults: {"controller": "frameworkBundle:default:401"}

localArea: 
  pattern:  /local
  defaults: {"controller": "frameworkBundle:default:401"}

basicArea: 
  pattern:  /basic
  defaults: {"controller": "frameworkBundle:default:401"}

digestArea: 
  pattern:  /digest
  defaults: {"controller": "frameworkBundle:default:401"}

### GOOGLE AUTH AREA ###
googleArea: 
  pattern:  /auth/google
  defaults: {"controller": "frameworkBundle:default:401"}

googleCallBackArea: 
  pattern:  /auth/google/callback
  defaults: {"controller": "frameworkBundle:default:401"}

### GITHUB AUTH AREA ###
githubArea: 
  pattern:  /auth/github
  defaults: {"controller": "frameworkBundle:default:401"}

githubCallBackArea: 
  pattern:  /auth/github/callback
  defaults: {"controller": "frameworkBundle:default:401"}

### UPLOAD ###
upload: 
  pattern:  /upload
  defaults: {"controller": "demoBundle:demo:indexUpload"}
  requirements: 
    method: GET

uploadFile: 
  pattern:  /fileupload
  defaults: {"controller": "demoBundle:demo:upload"}
  requirements: 
    method: POST

### ORM ###
orm: 
  pattern:  /sequelize
  defaults: {"controller": "demoBundle:demo:sequelize"}
  requirements: 
    method: GET

sql: 
  pattern:  /query/sql
  defaults: {"controller": "demoBundle:demo:querySql"}
  requirements: 
    method: GET
		
sqlJoin: 
  pattern:  /query/join
  defaults: {"controller": "demoBundle:demo:querySqlJoin"}
  requirements: 
    method: GET	


### SYSTEM ###
syscall: 
  pattern:  /syscall
  defaults: {"controller": "demoBundle:demo:syscall"}
  requirements: 
    method: GET	

httpRequest: 
  pattern:  /httpRequest
  defaults: {"controller": "demoBundle:demo:httpRequest"}
  requirements: 
    method: GET

xmlResponse: 
  pattern:  /xmlResponse
  defaults: {"controller": "demoBundle:demo:rawResponseSync"}
  requirements: 
    method: GET

xmlAsyncResponse: 
  pattern:  /xmlAsyncResponse
  defaults: {"controller": "demoBundle:demo:rawResponseAsync"}
  requirements: 
    method: GET	

### REALTIME ###
indexReal: 
  pattern:  /demo/realtime
  defaults: {"controller": "demoBundle:demo:indexRealTime"}
  requirements: 
    method: GET	

### FINDER ###
finder: 
  pattern:  /finder
  defaults: {"controller": "demoBundle:finder:index"}

download: 
  pattern:  /download
  defaults: {"controller": "demoBundle:finder:download"}
  requirements: 
    method: GET		

### WEBSOCKET ###
websoket: 
  pattern:  /websoket
  defaults: {"controller": "demoBundle:demo:websoket"}
  requirements:
    method:
      - GET
      - WEBSOCKET

### JSON ###
json: 
  pattern:  /json
  defaults: {"controller": "demoBundle:demo:json"}

### REDIRECT ###
redirect: 
  pattern:  /redirect
  defaults: {"controller": "demoBundle:demo:redirectGoogle"}
	


