########## nodefony CONFIG BUNDLE  unitTestBundle  ############
name :				unitTestBundle
locale :			en_en

mocha:
  nodefony:
    console:
      ui:       'bdd'
      reporter: 'list'          # spec | list
      timeout:  20000
