#!/usr/bin/env node

// nodefony
try {
	const nodefony  = require("nodefony");
}catch(e){
	const nodefony = require(".", "src", "nodefony", "core", "autoloader");
}

// START CONSOLE
process.env["MODE_START"] = "NODEFONY_CONSOLE" ;
const kernel = new nodefony.console( "prod", false, {
	node_start:process.env["MODE_START"]
});
