#!/usr/bin/env node
// --expose-gc --trace-gc --log-gc --trace-gc-verbose
//--debug
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
process.env.MODE_START = "NODEFONY_DEV" ;

///*var profiler = require('v8-profiler');
//var heapdump = require('heapdump');
//heapdump.writeSnapshot(process.cwd()+'/tmp/' + Date.now() + '.heapsnapshot', function(err, filename) {
//	console.log('heapdump written to', filename);
//});*/
try {
	const nodefony = require("nodefony");
}catch(e){
	const nodefony = require(".", "src", "nodefony", "core", "autoloader");
}

/*
 *
 * NODEFONY FRAMEWORK
 *
 *	KERNEL DEVELOPPEMENT
 *
 */
let environment = "dev" ;
let debug = true ;
const kernel = new nodefony.appKernel("SERVER", environment, ( process.env["NODEFONY_DEBUG"] || debug), {
		node_start:process.env["MODE_START"]
});

return kernel ;
