nodefony.Builder = class Builder {

  constructor(cli) {
    this.cli = cli;
    this.twig = twig;
    this.twigOptions = {
      views: this.cli.kernel.rootDir,
      'twig options': {
        async: false,
        cache: false
      }
    };
  }
  logger(pci, severity, msgid, msg) {
    try {
      if (!msgid) {
        msgid = "GENERATER";
      }
      return this.cli.logger(pci, severity, msgid, msg);
    } catch (e) {
      console.log(pci);
    }
  }

  buildSkeleton(skeleton, parse, obj, callback) {
    let skelete = null;
    try {
      skelete = new nodefony.fileClass(skeleton);
      if (skelete.type === "File") {
        if (parse !== false) {
          obj.settings = this.twigOptions;
          this.twig.renderFile(skelete.path, obj, callback);
        } else {
          callback(null, fs.readFileSync(skelete.path, {
            encoding: 'utf8'
          }));
        }
      } else {
        throw new Error(" skeleton must be file !!! : " + skelete.path);
      }
    } catch (e) {
      this.logger(e, "ERROR");
    }
    return skelete;
  }

  build(obj, parent, force) {
    let child = null;
    switch (nodefony.typeOf(obj)) {
    case "array":
      try {
        for (let i = 0; i < obj.length; i++) {
          this.build(obj[i], parent, force);
        }
      } catch (e) {
        this.logger(e, "ERROR");
        throw e;
      }
      break;
    case "object":
      for (let ele in obj) {
        let value = obj[ele];
        switch (ele) {
        case "name":
          var name = value;
          break;
        case "type":
          switch (value) {
          case "directory":
            try {
              child = this.cli.createDirectory(parent.path + "/" + name, "777", (ele) => {
                if (force) {
                  this.logger("Force Create Directory :" + ele.name);
                } else {
                  this.logger("Create Directory :" + ele.name);
                }
              }, force);
            } catch (e) {
              this.logger(e, "ERROR");
              throw e;
            }
            break;
          case "file":
            try {
              this.createFile(parent.path + "/" + name, obj.skeleton, obj.parse, obj.params, (ele) => {
                this.logger("Create File      :" + ele.name);
              });
            } catch (e) {
              this.logger(e, "ERROR");
              throw e;
            }
            break;
          case "symlink":
            try {
              if (force) {
                shell.ln('-sf', parent.path + "/" + obj.params.source, parent.path + "/" + obj.params.dest);
              } else {
                shell.ln('-s', parent.path + "/" + obj.params.source, parent.path + "/" + obj.params.dest);
              }
              this.logger("Create symbolic link :" + obj.name);
            } catch (e) {
              this.logger(e, "ERROR");
              throw e;
            }
            /*fs.symlink ( parent.path+"/"+obj.params.source, parent.path+"/"+obj.params.dest , obj.params.type || "file", (ele) => {
            this.logger("Create symbolic link :" + ele.name);
          } );*/
            break;
          }
          break;
        case "childs":
          try {
            this.build(value, child);
          } catch (e) {
            this.logger(e, "ERROR");
            throw e;
          }
          break;
        }
      }
      break;
    default:
      this.logger("generate build error arguments : ", "ERROR");
    }
    return child;
  }

  createFile(myPath, skeleton, parse, params, callback) {
    if (skeleton) {
      this.buildSkeleton(skeleton, parse, params, (error, result) => {
        if (error) {
          this.logger(error, "ERROR");
        } else {
          try {
            fs.writeFileSync(myPath, result, {
              mode: "777"
            });
            callback(new nodefony.fileClass(myPath));
          } catch (e) {
            throw e;
          }
        }
      });
    } else {
      let data = "/* generated by nodefony */";
      try {
        fs.writeFileSync(myPath, data, {
          mode: "777"
        });
        callback(new nodefony.fileClass(myPath));
      } catch (e) {
        throw e;
      }
    }
  }
};
module.exports = nodefony.Builder;