#
#        GENERATE BY NODEFONY CONFIG BUNDLE YAML FILE
#
# This file is YAML  FILE
# ---
# YAML:            YAML Ain't Markup Language
#
# What It Is:      YAML is a human friendly data serialization
#   standard for all programming languages.
#


########## NODEFONY CONFIG BUNDLE  monitoringBundle  ############
name :				     monitoringBundle
locale :			     en_en
debugBar:          true
forceDebugBarProd: false

#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        views:			true
#        translations: true
#
watch:             ~

realTimeBundle:
  services:
    monitoring:
      type:        tcp
      port:        1318
      domain:      localhost


storage:
  active:          true
  requests:        orm           # syslog
