security:
    firewalls:{}

#       monitoring_area:
#           pattern: ^/nodefony
#           provider: nodefony
#           form_login:
#             check_path: /nodefony
#             login_path: /login
#             default_target_path: /
#           FACTORY (strategy) AUTHENTICATION
#           passport-digest:
#             private_key: "Les sanglots longs Des violons De l’automne Blessent mon cœur D’une langueur Monotone."
#             realm: "nodefony"
#           context: ~
