#####################
#  NODEFONY FRAMEWORK
#
#       KERNEL CONFIG
#
#   Domain listen : Nodefony can listen only one domain ( no vhost )
#     Example :
#      domain :  0.0.0.0      # for all interfaces
#      domain :  [::1]        # for IPV6 only
#      domain :  192.168.1.1  # IPV4
#      domain :  mydomain.com # DNS
#
#   Domain Alias : string only "<<regexp>>" use domainCheck : true
#     Example :
#      domainAlias:
#        - "^127.0.0.1$"
#        - "^localhost$"
#        - ".*\\.nodefony\\.com"
#        - "^nodefony\\.eu$"
#        - "^.*\\.nodefony\\.eu$"
#

system:
  domain                        : 0.0.0.0
  domainAlias:
    - "^127.0.0.1$"
    - "^localhost$"
  httpPort                      : 5151
  httpsPort                     : 5152
  domainCheck                   : false
  statics                       : true
  security                      : true
  realtime                      : true
  monitoring                    : true
  documentation                 : true
  unitTest                      : true
  demo                          : true
  locale                        : "en_en"
  servers:
    protocol                    : "2.0"             #  2.0 || 1.1
    http                        : true
    https	                      : true
    ws			                    : true
    wss			                    : true
    certificats:
      key                       : "config/certificates/server/privkey.pem"
      cert                      : "config/certificates/server/fullchain.pem"
      ca                        : "config/certificates/ca/nodefony-root-ca.crt.pem"
      options:
        rejectUnauthorized      : true
  devServer:
    inline                      : true
    hot                         : false
    hotOnly                     : false
    overlay                     : true
    logLevel                    : info        # none, error, warning or info
    progress                    : false
    protocol                    : https
    websocket                   : true

  bundles:
    test-bundle                 : "file:src/bundles/test-bundle"
    #workbox-bundle              : "file:src/bundles/workbox-bundle"

  #################
  # SYSLOG NODEFONY
  log:
    active                      : true

##################
#       ASSETS CDN
#
#       You set cdn with string
#       CDN :    cdn.nodefony.com
#       or
#       CDN:
#          global: cdn.nodefony.com
#       or
#       CDN:
#         stylesheet:
#           - cdn.nodefony.com
#         javascript:
#           - cdn.nodefony.com
#         image:
#           - cdn.nodefony.com
#           - cdn.nodefony.fr
#         font:
#           - cdn.nodefony.com
CDN                             : ~

#################
# ENGINE TEMPLATE
#
#       TWIG
#       https://github.com/justjohn/twig.js
#
templating                      : twig

############
# ENGINE ORM
#       sequelize || mongoose
#orm                             : mongoose
orm                             : sequelize

#########################
# NODE.JS PACKAGE MANAGER
#
#       npm
#       yarn
#
packageManager                  : npm
