#
#
#	ROUTING BUNDLE monitoringBundle
#
#
#        GENERATE BY NODEFONY BUILDER YAML FILE
#
# This file is YAML  FILE
# ---
# YAML:                YAML Ain't Markup Language
#
# What It Is:          YAML is a human friendly data serialization
#   standard for all programming languages.
#
########## NODEFONY ROUTING  monitoringBundle  ############

monitoring-index:
  pattern:             /nodefony
  defaults: {"controller": "monitoring:default:index"}

monitoring-404:
  pattern:             /nodefony/404
  defaults: {"controller": "framework:default:404"}

monitoring-500:
  pattern:             /nodefony/500
  defaults: {"controller": "framework:default:500"}

monitoring-offline:
  pattern:             /nodefony/offline
  defaults: {"controller": "framework:default:500"}

monitoring-module:
  pattern:             /nodefony/modules/{module}
  defaults: {"controller": "monitoring:default:index"}

monitoring-realtime:
  pattern:             /nodefony/monitoring/realtime
  defaults: {"controller": "monitoring:default:realTime"}

monitoring-routes:
  pattern:             /nodefony/api/routes
  defaults: {"controller": "monitoring:api:routes"}
  requirements:
    method:            GET

monitoring-route:
  pattern:             /nodefony/api/route/{name}
  defaults: {"controller": "monitoring:api:routes"}
  requirements:
    method:            GET,DELETE,POST,PUT

monitoring-services:
  pattern:             /nodefony/api/services
  defaults: {"controller": "monitoring:api:services"}
  requirements:
    method:            GET

monitoring-service:
  pattern:             /nodefony/api/service/{name}
  defaults: {"controller": "monitoring:api:services"}
  requirements:
    method:            GET,DELETE,POST,PUT

monitoring-syslog:
  pattern:             /nodefony/api/syslog
  defaults: {"controller": "monitoring:api:syslog"}
  requirements:
    method:            GET ,WEBSOCKET

monitoring-requests:
  pattern:             /nodefony/api/requests
  defaults: {"controller": "monitoring:api:requests"}
  requirements:
    method:            GET

monitoring-request:
  pattern:             /nodefony/api/request/{uid}
  defaults: {"controller": "monitoring:api:request"}
  requirements:
    method:            GET

monitoring-config:
  pattern:             /nodefony/api/config
  defaults: {"controller": "monitoring:api:config"}
  requirements:
    method:            GET

monitoring-bundle:
  pattern:             /nodefony/api/config/{bundleName}
  defaults: {"controller": "monitoring:api:bundle"}
  requirements:
    method:            GET

monitoring-real:
  pattern:             /nodefony/api/realtime/{name}
  defaults: {"controller": "monitoring:api:realtime"}
  requirements:
    method:            GET

monitoring-users:
  pattern:             /nodefony/api/users
  defaults: {"controller": "monitoring:api:users"}
  requirements:
    method:            GET

monitoring-sessions:
  pattern:             /nodefony/api/sessions
  defaults: {"controller": "monitoring:api:sessions"}
  requirements:
    method:            GET

monitoring-pm2:
  pattern:             /nodefony/api/pm2/{action}
  defaults: {"controller": "monitoring:api:pm2"}
  requirements:
    method:            GET

monitoring-security:
  pattern:             /nodefony/api/security
  defaults: {"controller": "monitoring:api:security"}
  requirements:
    method:            GET

monitoring-test-load:
  pattern:             /nodefony/test/load
  defaults: {"controller": "monitoring:default:testLoad"}
  requirements:
    method:            WEBSOCKET
