#
#        nodefony APP CONFIG YAML FILE
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#

#####################
#
#  FRAMEWORK NODEFONY
#
#     APP CONFIG
name :                          AppBundle
version:                        1.0.0
locale :                        en_en

App:
  projectName:                  "nodefony"
  projectYear:                  2017
  locale:                       "en_en"
  authorName:                   "admin"
  authorMail:                   "admin@nodefony.com"

lang:
  en_en:                        "english"
  fr_fr:                        "français"


#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        config:        true		# only  routing.yml
#        views:			    true
#        translations:  true
#        webpack:       true
#
watch:				true


##################################
#
#       OVERRIDE BUNDLE MONITORING
#
#       see MONITORING BUNDLE config for more options
#
#
monitoringBundle:
  debugBar:                     true
  storage:
    active:                     true
    requests:                   orm


##################################
#
#       OVERRIDE  BUNDLE SEQUELIZE
#
#       see SEQUELIZE BUNDLE config for more options
#
#       Nodefony Database Management
#
#       By default nodefony create  connector name nodefony ( driver sqlite )
#       for manage Sessions / User
#
#
#       here create new databases connectors
#
#
sequelizeBundle:
  debug:        false
  connectors:
    nodefony:
      driver:          mysql
      dbname:          'nodefony'
      username:        'travis'
      password:        ''
      options:
        dialect:       mysql
        host:          127.0.0.1
        port:          '3306'


############################
#
#       OVERRIDE BUNDLE HTTP
#
#       see HTTP BUNDLE config for more options
#
#       // SERVICES
#       statics files
#       session
#       http server
#       https server
#       upload
#       websocket server
#       websocket secure server
#       sockjs dev server ( webpack dev server like WDS)
#
#
httpBundle:
  http:
    responseTimeout:              40000
  https:
    responseTimeout:              40000
  sockjs:
      overlay:                      true
      hot:                          true
      protocol:                     https
      websocket:                    true
  statics:
    defaultOptions:
      cacheControl :              true
      maxAge:                     0
    web:
      path:                       "web"
      options:
        maxAge:                   0                             #30*24*60*60*1000
  upload:
    tmp_dir:                      "tmp/upload"
    #max_filesize:                 100000                       #in Bytes
  session:
    start:                        false                         # autostart || false
    handler:                      session.storage.sequelize     # session.storage.files | session.storage.sequelize | session.storage.memcached
    #save_path:                    "./tmp/sessions"             # for session.storage.files only
    cookie:
      maxAge:                     0                             # like cookie_lifetime php  =>seconde
    memcached:
      servers:
        nodefony:
          location:               127.0.0.1
          port:                   11211
          weight:                 1



################################
#
#       OVERRIDE BUNDLE REALTIME
#
#       see REALTIME BUNDLE config for more options
#
#
realTimeBundle:
  services:
    monitoring:
      type:                       tcp
      port:                       1318
      domain:                     localhost
