realSecure:
  pattern:      /secure/realtime
  defaults: {"controller": "realtime:default:index"}
  requirements:
    method:     GET,POST,WEBSOCKET

real:
  pattern:      /realtime
  defaults: {"controller": "realtime:default:index"}
  requirements:
    method:     GET,POST,WEBSOCKET
