########## NODEFONY CONFIG BUNDLE  frameworkBundle  ############

#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        views:			true
#        translations:      true
#
watch                     : true

webpack:
  cache                   : true
  outputFileSystem        : "file-system"
  stats                    :
    colors                : true
    verbose               : true
    maxModules            : 16     #Infinity
  watchOptions:
    ignoreInitial         : false
    persistent            : true
    followSymlinks        : false
    depth                 : 0
    atomic                : false
    alwaysStat            : true
    ignorePermissionErrors: true
