########## NODEFONY CONFIG BUNDLE  frameworkBundle  ############

#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        views:			true
#        translations: true
#
watch                     : false

webpack:
  cache                   : true
  outputFileSystem        : "file-system"
  stats                    :
    colors                : true
    preset                : normal # normal || minimal || verbose || detailed  || summary
  watchOptions:
    aggregateTimeout      : 600
    poll                  : false
    followSymlinks        : true
