#
#        NODEFONY CONFIG BUNDLE YAML FILE
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/


########## NODEFONY CONFIG BUNDLE  securityBundle  ############
name :				securityBundle
version :			"2.0.0-beta"


#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true
#    or
#      watch:
#        controller:		true
#        views:			true
#        translations:          true
#
watch:                          false

cors:
    allow-origin:           "*"
    Access-Control:
      Access-Control-Allow-Methods:         "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers:         "ETag, Authorization,  X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date"
      Access-Control-Allow-Credentials:     true
      Access-Control-Expose-Headers:        "WWW-Authenticate ,X-Json"
      Access-Control-Max-Age:               10
