#
#
#	ROUTING BUNDLE jfoBundle
#
#===============================================================================
#
#  Copyright © 2017/2017     | 
#
# ===============================================================================
#
#        GENERATE BY raspberrypi BUILDER YAML FILE
#
# This file is YAML  FILE
#

########## raspberrypi ROUTING  jfoBundle  ############

jfo:
  pattern:  /jfo
  defaults: {"controller": "jfoBundle:default:index"}

login:
  pattern:  /login/ldap
  defaults: {"controller": "jfoBundle:login:loginLdap"}

logout:
  pattern:  /logout
  defaults: {"controller": "securityBundle:logout:logout"}

telnet-dashboard:
  pattern:  /telnet/dashboard
  defaults: {"controller": "jfoBundle:default:dashboard"}

rule-usb:
  pattern:  /telnet/usbrules/{device}
  defaults: {"controller": "jfoBundle:default:ruleUsb"}

conf-ser2net:
  pattern:  /telnet/ser2net/{device}
  defaults: {"controller": "jfoBundle:default:ser2net"}

telnet-shell:
  pattern:  /telnet/shell/{id}
  defaults: {"controller": "jfoBundle:devices:stream"}
  requirements:
    methdd:
      - WEBSOCKET

telnet-monitoring:
  pattern:  /telnet/monitoring/{id}
  defaults: {"controller": "jfoBundle:devices:monitoring"}
  requirements:
    methdd:
      - WEBSOCKET

telnet-exec:
  pattern:  /telnet
  defaults: {"controller": "jfoBundle:default:telnet"}
  requirements:
    method:
      - WEBSOCKET

raspi-view:
  pattern:  /raspi/{hostname}
  defaults: {"controller": "jfoBundle:devices:raspi"}
  