#
#   FIREWALL NODEFONY CONFIG
#
#   // example cross domain
#   firewalls   :
#      jfo_area:
#        pattern:                    ^/jfo
#        crossDomain:
#            allow-origin:           "*"
#            Access-Control:
#              Access-Control-Allow-Methods:         "GET, POST, PUT, DELETE, OPTIONS"
#              Access-Control-Allow-Headers:         "ETag, Authorization,  X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date"
#              Access-Control-Allow-Credentials:     true
#              Access-Control-Expose-Headers:        "WWW-Authenticate ,X-Json"
#              Access-Control-Max-Age:               10
#
#

security:
  firewalls   :
    ldap_efixo:
       pattern:                    ^/telnet
       provider:                   nodefony
       form_login:
         login_path:               /login/ldap
         default_target_path:      /telnet/dashboard
       passport-ldapauth:
        server: 
          url:                    'ldap://control-server.efixo.com'                
          searchBase:             'dc=efixo,dc=com'                
          searchFilter:           '(uid={{username}})'
        usernameField: 'email'
        passwordField: 'passwd'
        profile_wrapper:
          username:               "profile.uid"
          name:                   "profile.sn"
          surname:                "profile.givenName"
          email:                  "profile.mail"
          displayName:            "profile.cn"
       logout:                     /logout
       context:                    telnet