########## nodefony CONFIG BUNDLE  mongoBundle  ############
name        :              mongoBundle
version     :              "1.0.0"
type        :              "nodefony"
locale      :              en_en


#
#  WATCHERS
#
#    watchers Listen to changes, deletion, renaming of files and directories
#    of different components
#
#    For watch all components
#
#      watch:			true            # by default services false !
#    or
#      watch:
#        controllers     : true
#        config         :  true		# only  routing
#        views          :  true
#        translations   :  true
#        webpack        :  true
#        services       :  true
watch       :
  controllers    :         false
  config         :         false
  views          :         false
  translations   :         false
  webpack        :         false
  services       :         true

mongoose:
  debug:                   false
  connectors:
    nodefony:
      host:                "127.0.0.1"
      port:                11211
      dbname:              "nodefony"
      settings:
        user:              "nodefony"
        pass:              "nodefony"
        reconnectTries:    1000
        reconnectInterval: 10
        autoReconnect:     true
