#
#
#	CONFIG BUNDLE socketio-bundle
#
#===============================================================================
#
#  Copyright © 2018/2018        admin | admin@nodefony.com
#
#===============================================================================
#
#        GENERATE BY nodefony-core BUILDER YAML FILE
#
# This file is YAML  FILE
# ---
# YAML:               YAML Ain't Markup Language
#
# What It Is:         YAML is a human friendly data serialization
#   standard for all programming languages.
#


########## nodefony-core CONFIG BUNDLE  socketio-bundle  ############
type        :         "nodefony"
locale      :         en_en


#:w

#  WATCHERS
#
#    Listen to changes, deleting, renaming files and directories of different components
#
#    For watch all components
#
#      watch:			true            # by default services false !
#    or
#      watch:
#        controllers     : true
#        config         : true		# only  routing
#        views          : true
#        translations   : true
#        webpack        : true
#        services       : true
watch       :         true



socket.io:
  http       :        false
  https      :
    path     :        /socket.io
    namespace:
      chat    :
        pattern:      "/chat"
        defaults:     {
          controller: "socketio:default:chat"
          }
      events   :
        pattern:      "/events"
        defaults:     {
          controller: "socketio:default:events"
          }
