security:
    firewalls:{}
#
#       monitoring_area:
#           pattern:                    ^/nodefony
#           provider:                   nodefony
#           form_login:
#             check_path:               /nodefony
#             login_path:               /demo/login  
#             default_target_path:      /
           #FACTORY (strategy) AUTHENTICATION
#           passport-digest:
#             private_key:              "Les sanglots longs Des violons De l’automne Blessent mon cœur D’une langueur Monotone."
#             realm:                    "nodefony"
#           remember_me:                false           #TODO
#           logout:                     /logout
#           anonymous:                  ~
#           context:                    ~
#           stateless:                  false           #TODO
          

