#
#
#	CONFIG BUNDLE mail-bundle
#
#===============================================================================
#
#  Copyright © 2018/2019        admin | admin@nodefony.com
#
#===============================================================================
#
#        GENERATE BY nodefony-core BUILDER YAML FILE
#
# This file is YAML  FILE
# ---
# YAML:     YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#


########## nodefony-core CONFIG BUNDLE  mail-bundle  ############
type        : "nodefony"
locale      : en_en


#
#  WATCHERS
#
#    Listen to changes, deleting, renaming files and directories of different components
#
#    For watch all components
#
#      watch:			true            # by default services false !
#    or
#      watch:
#        controllers     : true
#        config         : true		# only  routing
#        views          : true
#        translations   : true
#        webpack        : true
#        services       : true
watch       : true

nodemailer :
  default       : "gmail"
  transporters  :
    #https://myaccount.google.com/security
    gmail :
      host      : "smtp.gmail.com"
      port      : 465
      secure    : true # true for 465, false for other ports
      auth:
        user    : "ccamensuli@gmail.com" #// generated ethereal user
        pass    : "xxx" #// generated ethereal password
    free :
      host      : "smtp.free.fr"
      port      : 465
      secure    : true # true for 465, false for other ports
      auth:
        user    : "ccamensuli" #// generated ethereal user
        pass    : "xxxxx" #// generated ethereal password
