name:                    nodefony
on:                      [push]
jobs:
  build-linux:
    runs-on:             ${{ matrix.os }}
    name:                Nodefony Build Linux
    strategy:
      matrix:
        os:              [ubuntu-latest]
        node-version:    [12.x, 14.x, 16.X]
    steps:
    - name:              Use latest NPM
      run:               sudo npm i -g --force npm
    - name:              Use latest Yarn
      run:               sudo npm i -g yarn
    - uses:              webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses:              actions/checkout@v2
    - name:              Use Node.js ${{ matrix.node-version }}
      uses:              actions/setup-node@v2
      with:
        node-version:    ${{ matrix.node-version }}
    # ACTION LOCAL TEST
    #- name:             Hello world action step
    #  id:               hello
    #  uses:             ./tools/actions/hello # Uses an action in the root directory
    #  with:
    #    who-to-greet:   'Nodefony Test Action'
    # Use the output from the `hello` step
    #- name:             Get the output time
    #  shell:            bash
    #  run:              echo "The time was ${{ steps.hello.outputs.time }}"
    - name:              npm install, build, and test
      shell:             bash
      run:               |
        npm cache clean --force
        npm install --no-audit --force --legacy-peer-deps
        npm install --no-audit --force --legacy-peer-deps ./src/nodefony
        npm run build --if-present
        npm run nodefony start
        sleep 120;
        npm test
      env:
        CI:              true
    services:
      nginx:
        image:           nginx
        ports:
          - 8080:80
        env:
          NGINX_PORT:    80
      redis:
        image:           redis
        ports:
          - 6379/tcp

  build-osx:
    runs-on:             ${{ matrix.os }}
    name:                Nodefony Build MacOS
    strategy:
      matrix:
        os:              [macOS-latest]
        node-version:    [12.x, 14.x, 16.X]
    steps:
    - name:              Use latest NPM
      run:               npm i -g --force npm
    - name:              Use latest Yarn
      run:               npm i -g yarn
    - uses:              webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses:              actions/checkout@v2
    - name:              Use Node.js ${{ matrix.node-version }}
      uses:              actions/setup-node@v2
      with:
        node-version:    ${{ matrix.node-version }}
    # ACTION LOCAL TEST
    #- name:             Hello world action step
    #  id:               hello
    #  uses:             ./tools/actions/hello # Uses an action in the root directory
    #  with:
    #    who-to-greet:   'Nodefony Test Action'
    # Use the output from the `hello` step
    #- name:             Get the output time
    #  shell:            bash
    #  run:              echo "The time was ${{ steps.hello.outputs.time }}"
    - name:              npm install, build, and test
      shell:             bash
      run:               |
        npm cache clean --force
        npm install --no-audit --force --legacy-peer-deps
        npm install --no-audit --force --legacy-peer-deps ./src/nodefony
        npm run build --if-present
        npm run nodefony start
        sleep 120;
        npm test
      env:
        CI:              true

  build-windows:
    runs-on:             ${{ matrix.os }}
    name:                Nodefony Build Windows
    strategy:
      matrix:
        os:              [windows-latest]
        node-version:    [12.x, 14.x, 16.X]
    steps:
    - name:              Use latest NPM on windows
      run:               npm i -g --force npm
    - name:              Use latest Yarn
      run:               npm i -g yarn
    - name:              Use clean Yarn cache on windows
      run:               yarn cache clean
    - uses:              actions/checkout@v2
    - name:              Use Node.js ${{ matrix.node-version }}
      uses:              actions/setup-node@v2
      with:
        node-version:    ${{ matrix.node-version }}
    # ACTION LOCAL TEST
    #- name:             Hello world action step
    #  id:               hello
    #  uses:             ./tools/actions/hello # Uses an action in the root directory
    #  with:
    #    who-to-greet:   'Nodefony Test Action'
    # Use the output from the `hello` step
    #- name:             Get the output time
    #  shell:            bash
    #  run:              echo "The time was ${{ steps.hello.outputs.time }}"
    - name:              Generate Certificates
      shell:             bash
      run:               |
        pwd
        openssl version -d
        npm rum certificates --if-present
    - name:              npm install, build, and test
      shell:             bash
      run:               |
        npm cache clean --force
        npm install --no-audit --force --legacy-peer-deps
        npm install --no-audit --force --legacy-peer-deps ./src/nodefony
        npm run build --if-present
        npm run nodefony start
        sleep 120;
        npm test
      env:
        CI:              true
