name:                  nodefony-core
on:                    [push]
jobs:
  build-linux:
    runs-on:           ubuntu-latest
    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version:  [12.x]
    steps:
    - uses:            actions/checkout@v1
    - name:            Use Node.js ${{ matrix.node-version }}
      uses:            actions/setup-node@v1
      with:
        node-version:  ${{ matrix.node-version }}
    - name:            npm install, build, and test
      run:             |
        git submodule sync
        git submodule update --init --recursive
        npm install
        npm link src/nodefony
        npm run build --if-present
        nodefony start
        sleep 60;
        npm test
      env:
        CI:            true

  build-osx:
    runs-on:           macOS-latest
    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version:  [12.x]
    steps:
    - uses:            actions/checkout@v1
    - name:            Use Node.js ${{ matrix.node-version }}
      uses:            actions/setup-node@v1
      with:
        node-version:  ${{ matrix.node-version }}
    - name:            npm install, build, and test
      run:             |
        git submodule sync
        git submodule update --init --recursive
        npm install
        npm link src/nodefony
        npm run build --if-present
        nodefony start
        sleep 60;
        npm test
      env:
        CI:            true

  build-windows:
    runs-on:           windows-latest
    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version:  [12.x]
    steps:
    - uses:            actions/checkout@v1
    - name:            Use Node.js ${{ matrix.node-version }}
      uses:            actions/setup-node@v1
      with:
        node-version:  ${{ matrix.node-version }}
    - name:            npm install, build, and test
      run:             |
        git submodule sync
        git submodule update --init --recursive
        npm install
        npm link src/nodefony
        npm run build --if-present
        nodefony start
        sleep 60;
        npm test
      env:
        CI:            true
